# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('target', models.CharField(choices=[('Heating', 'Heating'), ('Cooling', 'Cooling'), ('Lighting', 'Lighting'), ('Equipment', 'Equipment'), ('Others', 'Others')], default='Others', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
