# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_html_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic',
            fields=[
                ('html', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.html')),
                ('total_area', models.IntegerField()),
                ('condition_area', models.IntegerField()),
                ('uncondition_area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='electricity',
            fields=[
                ('html', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.html')),
                ('file', models.FileField(upload_to='C:/Users/obakatsu/Documents/Python_scripts/Django/EnergyPlus/data')),
            ],
        ),
    ]
