# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_basic_electricity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='html',
            name='html',
            field=models.FileField(upload_to=''),
        ),
    ]
