# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20160928_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='file',
            field=models.FileField(upload_to='electricity'),
        ),
        migrations.AlterField(
            model_name='html',
            name='html',
            field=models.FileField(upload_to='html/%Y/%m/%d/%M'),
        ),
    ]
