# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20160928_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='html',
            field=models.FileField(upload_to=project.models.dir_path),
        ),
    ]
