# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160928_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='location',
            field=models.CharField(choices=[('BJ', 'Beijing'), ('CH', 'China'), ('HK', 'Hong Kong'), ('JP', 'Japan'), ('SH', 'Shanghai'), ('SZ', 'Shenzhen'), ('TW', 'Taiwan')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
