# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_html_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
