# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20161101_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='location',
            field=models.CharField(choices=[('Beijing', 'Beijing'), ('China', 'China'), ('Hong Kong', 'Hong Kong'), ('Japan', 'Japan'), ('Shanghai', 'Shanghai'), ('Shenzhen', 'Shenzhen'), ('Taiwan', 'Taiwan')], max_length=15),
        ),
    ]
