# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20161101_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='diff',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='html',
            name='version',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
