# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20161101_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='unmet',
            fields=[
                ('html', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.html')),
                ('heating', models.FloatField()),
                ('cooling', models.FloatField()),
                ('ashrae', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='wwr',
            fields=[
                ('html', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.html')),
                ('total', models.FloatField()),
                ('north', models.FloatField()),
                ('east', models.FloatField()),
                ('south', models.FloatField()),
                ('west', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='basic',
            new_name='area',
        ),
    ]
