# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20161102_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='energy',
            fields=[
                ('html', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.html')),
                ('total', models.FloatField()),
                ('euipertotal', models.FloatField()),
                ('euipercondition', models.FloatField()),
            ],
        ),
    ]
