# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='loc',
            fields=[
                ('html', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.html')),
                ('cooling', models.CharField(default='test', max_length=100)),
                ('eui', models.CharField(default='test', max_length=100)),
                ('euicon', models.CharField(default='test', max_length=100)),
                ('energy', models.CharField(default='test', max_length=100)),
                ('fan', models.CharField(default='test', max_length=100)),
                ('glass', models.CharField(default='test', max_length=100)),
                ('heatbal', models.CharField(default='test', max_length=100)),
                ('hvac', models.CharField(default='test', max_length=100)),
                ('hw', models.CharField(default='test', max_length=100)),
                ('light', models.CharField(default='test', max_length=100)),
                ('oa', models.CharField(default='test', max_length=100)),
                ('oamin', models.CharField(default='test', max_length=100)),
                ('opaque', models.CharField(default='test', max_length=100)),
                ('pump', models.CharField(default='test', max_length=100)),
                ('unmet', models.CharField(default='test', max_length=100)),
                ('wwr', models.CharField(default='test', max_length=100)),
                ('wwrcon', models.CharField(default='test', max_length=100)),
            ],
        ),
    ]
