# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0004_auto_20161117_1523'),
        ('project', '0021_auto_20161117_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='ecms',
            field=models.ManyToManyField(to='ecm.ecm'),
        ),
    ]
