# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_html_ecms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='program',
            field=models.CharField(choices=[('Office', 'General office'), ('Residential', 'Residential'), ('Retail', 'Retail'), ('Restaurant', 'Restaurant'), ('Grocery', 'Grocery store'), ('Medilcal', 'Medilcal office'), ('Research', 'R&D or laboratory'), ('Hotel', 'Hotel'), ('Daycare', 'Daycare'), ('K-12', 'Educational,K-12'), ('Postsecondary', 'Educational,postsecondary'), ('Airport', 'Airport'), ('DataCenter', 'Data Center'), ('DistributionCenter', 'Distribution center,warehouse')], default='Retail', max_length=20),
        ),
    ]
