# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0004_auto_20161117_1523'),
        ('project', '0024_auto_20170131_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('epw', models.FileField(upload_to=project.models.epw_path)),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.location')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.program')),
            ],
        ),
        migrations.CreateModel(
            name='scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('LEED_v3_baseline', 'LEED_v3_baseline'), ('LEED_v4_baseline', 'LEED_v4_baseline'), ('BEAM+_baseline', 'BEAM+_baseline'), ('Proposed', 'Proposed')], default='BEAM+_baseline', max_length=30)),
                ('configuration', models.TextField()),
                ('ecms', models.ManyToManyField(blank=True, to='ecm.ecm')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='project.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='html',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='html',
            name='ecms',
        ),
        migrations.RemoveField(
            model_name='html',
            name='location',
        ),
        migrations.RemoveField(
            model_name='html',
            name='program',
        ),
        migrations.RemoveField(
            model_name='html',
            name='project',
        ),
        migrations.RemoveField(
            model_name='html',
            name='user',
        ),
        migrations.AddField(
            model_name='html',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='html', to='project.scheme'),
            preserve_default=False,
        ),
    ]
