# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('sensibleH', models.FloatField()),
                ('sensibleC', models.FloatField()),
                ('surfaceH', models.FloatField()),
                ('surfaceC', models.FloatField()),
                ('peopleH', models.FloatField()),
                ('lightH', models.FloatField()),
                ('equipH', models.FloatField()),
                ('windowH', models.FloatField()),
                ('transferH', models.FloatField()),
                ('infiltrationH', models.FloatField()),
                ('conductionH', models.FloatField()),
                ('equipR', models.FloatField()),
                ('windowR', models.FloatField()),
                ('transferR', models.FloatField()),
                ('infiltrationR', models.FloatField()),
                ('conductionR', models.FloatField()),
            ],
            options={
                'ordering': ('project',),
            },
        ),
    ]
